### ISSUE TITLE
Memory Leak on Raspberry Pi 3B when playing audio files

### ISSUE THREAD

**Issue by tomhaines** [pyglet/pyglet#283]
When using pyglet.media to play a playlist of music MP3s on a Raspberry Pi 3B, memory usage continually increases until system starts thrashing

OS: Raspbian 10
Python: 3.7.3
Pyglet: 1.5.7
FFMPEG: 4.1.6-1~deb10u1+rpt2

The following code reproduces the error. It reads a list of MP3's from a directory of about 30 files each about 2-3 minutes long. The program initially consumes 420MB, but grows to 1.98GB by the time the system becomes unresponsive

The following code was used to reproduce the issue consistently
```
import pyglet
import os

path = '/path/to/directory/containing/mp3s'

pool = []
for root, dirs, files in os.walk(path, followlinks = True) :
  for name in files :
    pool.append(os.path.join(root, name))

player = pyglet.media.Player()

def queue_next() :
  s = pool.pop(0)
  print("Queueing: %s" % (s))
  player.queue(pyglet.media.load(s))
  pool.append(s) #put the item back on the end of the playlist so we never run out of songs to play

def on_eos() :
  player.next_source()
  queue_next()

player.on_eos = on_eos

queue_next()
queue_next()
player.play()

window = pyglet.window.Window(100,100,)

pyglet.app.run()
```

**Comment by caffeinepills** [comment]
Most likely your sources are not getting freed after you play them for some reason. `pyglet.media.load` doesn't cache anything, so it's going to continue loading the same files into memory as it loops.

My suggestion would be to try to, at some number of played songs, manually free the sources returned from `pyglet.media.load` (`del source`). Either that or just cache all of them into memory and re-use the sources instead of creating new ones.

**Comment by tomhaines** [comment]
Are you suggesting that as a workaround? I have no other references to the source other than passing it to the player to queue. Shouldn't the player be deleting the source after it has played it? I'm happy to try this, just want to understand if I'm doing something incorrectly here. My assumption is that the GC would delete the source after the player had finished it.

**Comment by tomhaines** [comment]
Wondering if there's been any further development on this? I've switched to a kludgy VLC based solution in the interim but would love to use pyglet for audio.

**Comment by benmoran56** [comment]
It looks like there is an issue with the GStreamerDecoder not releasing sources after they're exhausted. 
Could you confirm which decoder is in use on your Pi? A simple print should do it: 
```py
src = pyglet.media.load('sourcepath.mp3')
print(src)
```

**Comment by tomhaines** [comment]
<pyglet.media.codecs.gstreamer.GStreamerSource object at 0xb66e1b10>

**Comment by tomhaines** [comment]
I ran the above code with both GStreamerDecoder and FFmpegDecoder, and I can confirm that with GStreamerDecoder memory usage continues to grow during playback. But when I use FFmpegDecoder memory usage remains stable.

Please let me know if I can provide any additional information to help debug this.

**Comment by benmoran56** [comment]
Hi Tom, thanks for confirming. I have just pushed a fix for this, which will be in the `pyglet-1.5-maintenance` branch. 
This will be in the next point release, but you can install it directly from Github with something like: 
```
pip install --user --upgrade git+http://github.com/pyglet/pyglet@pyglet-1.5-maintenance
```
If you have a chance to try that, let me know how it goes.

**Comment by tomhaines** [comment]
Unfortunately I still see the growing memory consumption with the above script using GStreamer decoder. And confirming Pyglet version 1.5.16

**Comment by benmoran56** [comment]
I tried your code on my local machine, and the memory isn't growing at all. It holds stead at about ~45MB of usage. 

To troubleshoot on your local machine, you could try: 
- Add a `print(player._playlists)` when queuing new sources to see if your Player queue is getting exhausted properly.  In my case, it's always sitting at two objects. 
- Make sure you're actually using GStreamer: 
```py
src = pyglet.media.load(s)
print("Loaded Source: ", src)
player.queue(src)
```
- At the very top of your program, add a monkey-patched `__del__` method on GStreamerSource so that you can see if it's getting cleaned up correctly. You should expect to see a message printed every time a new source is queued: 
```py
def my_del(self):
        self.delete()
        print("Cleaning up Source: ", self)

pyglet.media.codecs.gstreamer.GStreamerSource.__del__ = my_del
```

The Gstreamer fixes were added fairly recently, so you might want to try reinstalling and make sure pip isn't using a cached version.

**Comment by tomhaines** [comment]
Thanks for the help. I've uninstalled Pyglet, and cleared the cache, and re-installed the maintenance branch, and I'm still seeing the memory usage grow continuously.

> pi@Radiolux:~ $ pip3 cache purge
> Files removed: 65
> pi@Radiolux:~ $ pip3 uninstall pyglet
> Found existing installation: pyglet 1.5.16
> Uninstalling pyglet-1.5.16:
>   Would remove:
>     /home/pi/.local/lib/python3.7/site-packages/pyglet-1.5.16.dist-info/*
>     /home/pi/.local/lib/python3.7/site-packages/pyglet/*
> Proceed (y/n)? y
>   Successfully uninstalled pyglet-1.5.16
> pi@Radiolux:~ $ pip3 cache purge
> ERROR: No matching packages
> pi@Radiolux:~ $ pip3 install --user --upgrade git+http://github.com/pyglet/pyglet@pyglet-1.5-maintenance
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Collecting git+http://github.com/pyglet/pyglet@pyglet-1.5-maintenance
>   Cloning http://github.com/pyglet/pyglet (to revision pyglet-1.5-maintenance) to /tmp/pip-req-build-8dcbapqn
>   Running command git clone -q http://github.com/pyglet/pyglet /tmp/pip-req-build-8dcbapqn
>   Running command git checkout -b pyglet-1.5-maintenance --track origin/pyglet-1.5-maintenance
>   Switched to a new branch 'pyglet-1.5-maintenance'
>   Branch 'pyglet-1.5-maintenance' set up to track remote branch 'pyglet-1.5-maintenance' from 'origin'.
> Building wheels for collected packages: pyglet
>   Building wheel for pyglet (setup.py) ... done
>   Created wheel for pyglet: filename=pyglet-1.5.16-py3-none-any.whl size=1120569 sha256=9c4d5a50628b6313d476e93990b4c6e7ccd13e18dbb735fe6a595b694ae42af4
>   Stored in directory: /tmp/pip-ephem-wheel-cache-rqrgnv34/wheels/09/d1/5c/0ad5b62d92106582e38894d11d8240cd55f95b4a06f2ee5c06
> Successfully built pyglet
> Installing collected packages: pyglet
> Successfully installed pyglet-1.5.16

Here is the latest code:

`
import pyglet
import os

path = '/media/pi/Radiolux/Media/Music'
print("Pyglet: %s" % pyglet.version)
pool = []
for root, dirs, files in os.walk(path, followlinks = True) :
  for name in files :
    pool.append(os.path.join(root, name))

import random
random.shuffle(pool)

player = pyglet.media.Player()
#pyglet.options['audio'] = ('openal')
player.volume = 0.1

def queue_next() :
  print(player._playlists)
  s = pool.pop(0)
  print("Queueing: %s" % (s))
  source = pyglet.media.load(s)
  print("Loaded Source: ", source)
  player.queue(source)#, decoder=pyglet.media.codecs.ffmpeg.FFmpegDecoder())
  
  pool.append(s) #put the item back on the end of the playlist so we never run out of songs to play

def on_eos() :
  player.next_source()
  queue_next()

def my_del(self) :
  self.delete()
  print("Cleaning up Source: ", self)
  
pyglet.media.codecs.gstreamer.GStreamerSource.__del__ = my_del

player.on_eos = on_eos

queue_next()
queue_next()
player.play()

window = pyglet.window.Window(100,100,)

pyglet.app.run()
`

Here is the output

> pi@Radiolux:~/Documents/Radiolux $ python3 util/mem-test-05.py 
> Pyglet: 1.5.16
> deque([])
> Queueing: /media/pi/Radiolux/Media/Music/WWII Greatest Radio Songs/2-17 Baby It's Cold Outside 1.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xb62573b0>
> deque([<generator object _one_item_playlist at 0xb4ffe0b0>])
> Queueing: /media/pi/Radiolux/Media/Music/WWII Greatest Radio Songs/2-05 Dearly Beloved.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf077e50>
> Cleaning up Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xb62573b0>
> deque([<generator object _one_item_playlist at 0xb4ffe4f0>])
> Queueing: /media/pi/Radiolux/Media/Music/Great Songs of WWII/08 G.I. Jive.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xb4fed3f0>
> Cleaning up Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf077e50>
> deque([<generator object _one_item_playlist at 0xb4ffe0b0>])
> Queueing: /media/pi/Radiolux/Media/Music/WWII Greatest Radio Songs/2-10 Miss You.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf07f770>
> Cleaning up Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xb4fed3f0>
> deque([<generator object _one_item_playlist at 0xb4ffe4f0>])
> Queueing: /media/pi/Radiolux/Media/Music/WWII Greatest Radio Songs/2-07 Moonlight Becomes You.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf077210>
> Cleaning up Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf07f770>
> deque([<generator object _one_item_playlist at 0xb4ffe0b0>])
> Queueing: /media/pi/Radiolux/Media/Music/WWII Greatest Radio Songs/1-27 A Boy In Khaki, A Girl In Lace.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf077e50>
> Cleaning up Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf077210>
> deque([<generator object _one_item_playlist at 0xb4ffe4f0>])
> Queueing: /media/pi/Radiolux/Media/Music/WWII Greatest Radio Songs/1-11 Taking A Chance On Love.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf0771f0>
> Cleaning up Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf077e50>
> deque([<generator object _one_item_playlist at 0xb4ffe0b0>])
> Queueing: /media/pi/Radiolux/Media/Music/WWII Greatest Radio Songs/2-16 Whispering Grass.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf07f710>
> Cleaning up Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf0771f0>
> deque([<generator object _one_item_playlist at 0xb4ffe4f0>])
> Queueing: /media/pi/Radiolux/Media/Music/WWII Memories/11 Five Minutes More.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf077330>
> Cleaning up Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf07f710>
> deque([<generator object _one_item_playlist at 0xb4ffe0b0>])
> Queueing: /media/pi/Radiolux/Media/Music/Great Songs of WWII/12 I'll Be Seeing You.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf07f6f0>
> Cleaning up Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf077330>
> deque([<generator object _one_item_playlist at 0xb4ffe4f0>])
> Queueing: /media/pi/Radiolux/Media/Music/WWII Memories/23 Please Leave My Butter Alone.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf07f710>
> Cleaning up Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf07f6f0>
> deque([<generator object _one_item_playlist at 0xb4ffe0b0>])
> Queueing: /media/pi/Radiolux/Media/Music/WWII Memories/57 Where Does Poor Pa Go In The Black-Out_.mp3
> Loaded Source:  <pyglet.media.codecs.gstreamer.GStreamerSource object at 0xaf07f6f0>


And here is the memory growth

> while true; do pmap 19323 | tail -n 1; sleep 10; done
>  total   486700K
>  total   487724K
>  total   489772K
>  total   491820K
>  total   492844K
>  total   494892K
>  total   496940K
>  total   498988K
>  total   500012K
>  total   502060K
>  total   504108K
>  total   505808K
>  total   507680K
>  total   509540K
>  total   511596K
>  total   513504K
>  total   515204K
>  total   517288K
>  total   519020K
>  total   520804K
>  total   522828K
>  total   524696K
>  total   526668K
>  total   528612K
>  total   530552K
>  total   532400K
>  total   534200K
>  total   535608K
>  total   537656K
>  total   539704K
>  total   540728K
>  total   542776K
>  total   544824K
>  total   546872K
>  total   547896K
>  total   549944K
>  total   551992K
>  total   553016K
>  total   555064K
>  total   557112K
>  total   558136K
>  total   560184K
>  total   562232K
>  total   564280K
>  total   565304K
>  total   567352K
>  total   568376K
>  total   571120K
>  total   572960K
>  total   574760K
>  total   576668K
>  total   578616K
>  total   580512K
>  total   582500K
>  total   584520K
>  total   586168K
>  total   588004K
>  total   589988K
>  total   591796K
>  total   593804K
>  total   595780K
>  total   597428K
>  total   599284K
>  total   600988K
>  total   603036K
>  total   605084K
>  total   606108K
>  total   608156K
>  total   610204K
>  total   612252K
>  total   613276K
>  total   615324K
>  total   617372K
>  total   618396K
>  total   620444K
>  total   622492K
>  total   623516K
>  total   625564K
>  total   627612K
>  total   629660K
>  total   630684K
>  total   632732K
>  total   633756K
>  total   635624K
>  total   637388K
>  total   639216K
>  total   641112K
>  total   643052K
>  total   644988K
>  total   646792K
>  total   648824K
>  total   650536K
>  total   652336K
>  total   654264K
>  total   656188K
>  total   658152K
>  total   660152K
>  total   661920K
>  total   663716K
>  total   665668K
>  total   668404K
>  total   670596K
>  total   671620K
>  total   673668K
>  total   675716K
>  total   676740K
>  total   678788K
>  total   680836K
>  total   682884K
>  total   683908K
>  total   685956K
>  total   688004K
>  total   689028K
>  total   691076K
>  total   693124K
>  total   695172K
>  total   696196K
>  total   698244K
>  total   700292K
>  total   701640K
>  total   703688K
>  total   705736K
>  total   707784K
>  total   708808K
>  total   710856K
>  total   712904K
>  total   713928K
>  total   715976K
>  total   718024K
>  total   720072K
>  total   721096K
>  total   723144K
>  total   725192K
>  total   726216K
>  total   728264K
>  total   730312K
>  total   732360K
>  total   733384K
>  total   735432K
>  total   737480K
>  total   738504K
>  total   740552K
>  total   742600K
>  total   743624K
>  total   745672K
>  total   747720K
>  total   749768K
>  total   750792K

**Comment by benmoran56** [comment]
That's pretty strange.. the "Cleaning up Source" messages should be pretty sure that the sources are getting garbage collected.

If you're able to do this same test, except with a folder of `.wav` files, then it might help confirm if there is a leak elsewhere.

**Comment by benmoran56** [comment]
Just wondering if you were ever able to test this with `.wav` files, instead of compressed audio?

**Comment by tomhaines** [comment]
Thanks for the reminder. I'll be able to test this weekend.

**Comment by benmoran56** [comment]
Ok great!
Make sure to install the latest release beforehand:
```
pip install --upgrade --user pyglet
```

**Comment by tomhaines** [comment]
I can confirm that when I run this code with MP3 files, memory continues to grow. When I run it against WAV files memory usage stays constant.

**Comment by benmoran56** [comment]
Thanks for test.
That pretty much confirms that it's the Gstreamer decoder, and not the audio backend. (Since WAV files don't need special decoding). 

I can't replicate the memory leak on my end, but I **did** discover a potential issue with dangling file pointers. 
I put a fix into the `pyglet-1.5-maintenance` branch. Please give that a try, and see if it has any positive effect for you. 
You can either grab the branch directly, or if you'r using pip to install: 
```py
pip install --user --upgrade git+http://github.com/pyglet/pyglet.git@pyglet-1.5-maintenance
```

Also, have a peek at the open files for your application process (before and after) and see if there is any change: 
```sh
# for example if "4189" was your process id:
ls -al /proc/4189/fd
```

**Comment by tomhaines** [comment]
Upgrading to the latest maintenance branch doesn't fix anything unfortunately. But it does look like files are getting closed out properly.

The version of GStreamer on Raspbian is 1.14-4.1 which is out of date. I won't be able to update GStreamer on this Raspberry Pi, so I can't really test if there's a bug there that may have already been fixed. 

I have switched over to WAV files on this project anyway, so I'm not encountering this issue any longer.

Thanks for your help. If you need anything else tested, I'm happy to help.

**Comment by benmoran56** [comment]
It does seem like the leak is somewhere inside of GStreamer.
The next best course of action would be to test with a different distribution that contains builds of GStreamer. 
Maybe something like Arch Linux Arm?

**Comment by tomhaines** [comment]
I just updated to Debian Bullseye which includes GStreamer 1.18.4-2 and can confirm that the memory leaks have stopped. I've been running for eight hours straight, and RAM consumption is stable.

**Comment by benmoran56** [comment]
I'm glad that it's finally working after all this time, and thanks for updating the ticket. That's information for others who might run into this issue.

I'll close this finally :+1:
