### ISSUE TITLE
OSError caused by Label on Windows 7

### ISSUE THREAD

**Issue by DreamAlone666** [pyglet/pyglet#699]
I have installed the new pyglet2.0. When I use FPSDisplay, it crashes and raises `OSError: [WinError -2147024809]`.

When I try `label = pyglet.text.Label('str')`, I get the same result. So I speculate this is a problem of `Label`.

I run them on two win7 computers with python-3.8.10-embed. They worked fine with pyglet1.5.

Is it a bug? I didn't do anything but to create one `Label` and call `app.run()`.

**Comment by benmoran56** [comment]
Hi, 

pyglet 2.0 has new hardware requirements, such as OpenGL 3.3+ compatible drivers. 
To comfirm, please post the output of `python -m pyglet.info`

**Comment by einarf** [comment]
Does win7 even have the new directdraw text stuff?

**Comment by DreamAlone666** [comment]
Platform
------------------------------------------------------------------------------
platform:  Windows-7-6.1.7601-SP1
release:   7
machine:   AMD64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
sys.maxint: 9223372036854775807
os.getcwd(): D:\Program Files\Temp

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.0
pyglet.compat_platform: win32
pyglet.__file__: D:\Program Files\Temp\pyecs\pyglet\__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.win32.Win32Display object at 0x00000000030F74F0>
screens[0]: Win32Screen(x=0, y=0, width=1440, height=900)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 32
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 8
config['depth_size'] = 24
config['stencil_size'] = 8
config['accum_red_size'] = 16
config['accum_green_size'] = 16
config['accum_blue_size'] = 16
config['accum_alpha_size'] = 16
config['major_version'] = 3
config['minor_version'] = 3
config['forward_compatible'] = None
config['opengl_api'] = 'gl'
config['debug'] = None
context: Win32ARBContext(id=41344832, share=Win32Context(id=51105552, share=None))

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (3, 3)
gl_info.get_vendor(): Intel
gl_info.get_renderer(): Intel(R) HD Graphics
gl_info.get_extensions():
   GL_3DFX_texture_compression_FXT1
   GL_ARB_ES2_compatibility
   GL_ARB_ES3_compatibility
   GL_ARB_arrays_of_arrays
   GL_ARB_base_instance
   GL_ARB_blend_func_extended
   GL_ARB_buffer_storage
   GL_ARB_color_buffer_float
   GL_ARB_compressed_texture_pixel_storage
   GL_ARB_conservative_depth
   GL_ARB_copy_buffer
   GL_ARB_debug_output
   GL_ARB_depth_buffer_float
   GL_ARB_depth_clamp
   GL_ARB_depth_texture
   GL_ARB_draw_buffers
   GL_ARB_draw_buffers_blend
   GL_ARB_draw_elements_base_vertex
   GL_ARB_draw_indirect
   GL_ARB_draw_instanced
   GL_ARB_explicit_attrib_location
   GL_ARB_fragment_coord_conventions
   GL_ARB_fragment_program
   GL_ARB_fragment_program_shadow
   GL_ARB_fragment_shader
   GL_ARB_framebuffer_no_attachments
   GL_ARB_framebuffer_object
   GL_ARB_framebuffer_sRGB
   GL_ARB_geometry_shader4
   GL_ARB_get_program_binary
   GL_ARB_gpu_shader5
   GL_ARB_gpu_shader_fp64
   GL_ARB_half_float_pixel
   GL_ARB_half_float_vertex
   GL_ARB_instanced_arrays
   GL_ARB_internalformat_query
   GL_ARB_internalformat_query2
   GL_ARB_map_buffer_alignment
   GL_ARB_map_buffer_range
   GL_ARB_multi_draw_indirect
   GL_ARB_multisample
   GL_ARB_multitexture
   GL_ARB_occlusion_query
   GL_ARB_occlusion_query2
   GL_ARB_pixel_buffer_object
   GL_ARB_point_parameters
   GL_ARB_point_sprite
   GL_ARB_program_interface_query
   GL_ARB_provoking_vertex
   GL_ARB_robustness
   GL_ARB_sample_shading
   GL_ARB_sampler_objects
   GL_ARB_seamless_cube_map
   GL_ARB_separate_shader_objects
   GL_ARB_shader_atomic_counters
   GL_ARB_shader_bit_encoding
   GL_ARB_shader_objects
   GL_ARB_shader_precision
   GL_ARB_shader_subroutine
   GL_ARB_shading_language_100
   GL_ARB_shading_language_420pack
   GL_ARB_shading_language_packing
   GL_ARB_shadow
   GL_ARB_stencil_texturing
   GL_ARB_sync
   GL_ARB_tessellation_shader
   GL_ARB_texture_border_clamp
   GL_ARB_texture_buffer_object_rgb32
   GL_ARB_texture_buffer_range
   GL_ARB_texture_compression
   GL_ARB_texture_compression_bptc
   GL_ARB_texture_compression_rgtc
   GL_ARB_texture_cube_map
   GL_ARB_texture_cube_map_array
   GL_ARB_texture_env_add
   GL_ARB_texture_env_combine
   GL_ARB_texture_env_crossbar
   GL_ARB_texture_env_dot3
   GL_ARB_texture_float
   GL_ARB_texture_gather
   GL_ARB_texture_multisample
   GL_ARB_texture_non_power_of_two
   GL_ARB_texture_query_lod
   GL_ARB_texture_rectangle
   GL_ARB_texture_rg
   GL_ARB_texture_rgb10_a2ui
   GL_ARB_texture_storage
   GL_ARB_texture_storage_multisample
   GL_ARB_texture_swizzle
   GL_ARB_timer_query
   GL_ARB_transform_feedback2
   GL_ARB_transform_feedback3
   GL_ARB_transform_feedback_instanced
   GL_ARB_transpose_matrix
   GL_ARB_uniform_buffer_object
   GL_ARB_vertex_array_bgra
   GL_ARB_vertex_array_object
   GL_ARB_vertex_attrib_64bit
   GL_ARB_vertex_attrib_binding
   GL_ARB_vertex_buffer_object
   GL_ARB_vertex_program
   GL_ARB_vertex_shader
   GL_ARB_vertex_type_2_10_10_10_rev
   GL_ARB_viewport_array
   GL_ARB_window_pos
   GL_ATI_separate_stencil
   GL_EXT_abgr
   GL_EXT_bgra
   GL_EXT_blend_color
   GL_EXT_blend_equation_separate
   GL_EXT_blend_func_separate
   GL_EXT_blend_minmax
   GL_EXT_blend_subtract
   GL_EXT_clip_volume_hint
   GL_EXT_compiled_vertex_array
   GL_EXT_draw_buffers2
   GL_EXT_draw_range_elements
   GL_EXT_fog_coord
   GL_EXT_framebuffer_blit
   GL_EXT_framebuffer_multisample
   GL_EXT_framebuffer_object
   GL_EXT_geometry_shader4
   GL_EXT_gpu_program_parameters
   GL_EXT_gpu_shader4
   GL_EXT_multi_draw_arrays
   GL_EXT_packed_depth_stencil
   GL_EXT_packed_float
   GL_EXT_packed_pixels
   GL_EXT_rescale_normal
   GL_EXT_secondary_color
   GL_EXT_separate_specular_color
   GL_EXT_shader_integer_mix
   GL_EXT_shadow_funcs
   GL_EXT_stencil_two_side
   GL_EXT_stencil_wrap
   GL_EXT_texture3D
   GL_EXT_texture_array
   GL_EXT_texture_buffer
   GL_EXT_texture_compression_s3tc
   GL_EXT_texture_edge_clamp
   GL_EXT_texture_env_add
   GL_EXT_texture_env_combine
   GL_EXT_texture_filter_anisotropic
   GL_EXT_texture_integer
   GL_EXT_texture_lod_bias
   GL_EXT_texture_rectangle
   GL_EXT_texture_sRGB
   GL_EXT_texture_sRGB_decode
   GL_EXT_texture_shared_exponent
   GL_EXT_texture_snorm
   GL_EXT_texture_storage
   GL_EXT_texture_swizzle
   GL_EXT_transform_feedback
   GL_IBM_texture_mirrored_repeat
   GL_INTEL_map_texture
   GL_INTEL_performance_queries
   GL_INTEL_performance_query
   GL_KHR_blend_equation_advanced
   GL_KHR_debug
   GL_NV_blend_square
   GL_NV_conditional_render
   GL_NV_primitive_restart
   GL_NV_texgen_reflection
   GL_SGIS_generate_mipmap
   GL_SGIS_texture_edge_clamp
   GL_SGIS_texture_lod
   GL_SUN_multi_draw_arrays
   GL_WIN_swap_hint
   WGL_ARB_buffer_region
   WGL_ARB_create_context
   WGL_ARB_create_context_profile
   WGL_ARB_create_context_robustness
   WGL_ARB_extensions_string
   WGL_ARB_framebuffer_sRGB
   WGL_ARB_make_current_read
   WGL_ARB_multisample
   WGL_ARB_pbuffer
   WGL_ARB_pixel_format
   WGL_ARB_pixel_format_float
   WGL_EXT_create_context_es2_profile
   WGL_EXT_create_context_es_profile
   WGL_EXT_depth_float
   WGL_EXT_extensions_string
   WGL_EXT_pixel_format_packed_float
   WGL_EXT_swap_control
   WGL_EXT_swap_control_tear
   WGL_NV_DX_interop

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.directsound.adaptation.DirectSoundDriver object at 0x0000000002736B80>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
OpenAL not available.

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.

**Comment by benmoran56** [comment]
@einarf 
pyglet _should_ automatically fall back to the legacy GDI font renderer on older systems. 
in `pyglet.font.__init__.py`:
```py
        if WINDOWS_7_OR_GREATER and not pyglet.options['win32_gdi_font']:
            from pyglet.font.directwrite import Win32DirectWriteFont
            _font_class = Win32DirectWriteFont
        else:
            from pyglet.font.win32 import GDIPlusFont
            _font_class = GDIPlusFont
```

**Comment by benmoran56** [comment]
@DreamAlone666 
Can you post the full Python traceback? 

In the pyglet.info output, the driver reports that it supports OpenGL 3.3.
The `OSError: [WinError -2147024809]` error message, however, means "invalid argument/parameter". This is an OS level error, and points toward a driver issue. There may be some OpenGL call or feature that we're using that is not fully implemented by the driver.  

Is there an updated driver available for your GPU? 
Is this a laptop integrated GPU?

**Comment by DreamAlone666** [comment]
@benmoran56
Not a laptop. Intel G2030 integrated GPU. After the error, I have already updated the driver once, but in vain.

The full python traceback:

Traceback (most recent call last):
  File "d:/Program Files/Temp/pyecs/aaa.py", line 4, in <module>
    label = pyglet.text.Label('emmm')
  File "d:\Program Files/Temp/pyecs\pyglet\text\__init__.py", line 479, in __init__
    super().__init__(doc, x, y, z, width, height, anchor_x, anchor_y, multiline, dpi, batch, group, rotation)
  File "d:\Program Files/Temp/pyecs\pyglet\text\__init__.py", line 276, in __init__
    super().__init__(document, width, height, multiline, dpi, batch, group)
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 938, in __init__
    self.document = document
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 989, in document
    self._init_document()
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 1461, in _init_document
    self._update()
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 1375, in _update
    lines = self._get_lines()
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 1352, in _get_lines
    glyphs = self._get_glyphs()
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 1509, in _get_glyphs
    glyphs.extend(font.get_glyphs(text[start:end]))
  File "d:\Program Files/Temp/pyecs\pyglet\font\directwrite.py", line 2153, in get_glyphs
    self._empty_glyph = self._glyph_renderer.render_using_layout(" ")
  File "d:\Program Files/Temp/pyecs\pyglet\font\directwrite.py", line 1845, in render_using_layout
    self._render_target.EndDraw(None, None)
  File "d:\Program Files/Temp/pyecs\pyglet\libs\win32\com.py", line 150, in _call
    ret = self.method.get_field()(self.i, self.name)(obj, *args)
  File "_ctypes/callproc.c", line 998, in GetResult
OSError: [WinError -2147024809] 参数错误。

**Comment by benmoran56** [comment]
It looks like it's trying to use the new DirectWrite font renderer, but that might not work on Windows 7. To force the usage of the legacy GDI renderer, set  `pyglet.options['win32_gdi_font'] = True` at the start of your program, immediately after importing pyglet:
```py
import pyglet
pyglet.options['win32_gdi_font'] = True
```

**Comment by DreamAlone666** [comment]
It works. Thanks!

You are right. Windows 7 usually supports DX11, while DirectWrite is available in DX11.1.

**Comment by caffeinepills** [comment]
I think this is the fact that certain things aren't renderable using Windows 7. It may be the default color options. Could you try (without the `win32_gdi_font`) if changing this to 0 works. https://github.com/pyglet/pyglet/blob/master/pyglet/font/directwrite.py#L1553

Or this may work (put right after `import pyglet`)
```py
from pyglet.font.directwrite import DirectWriteGlyphRenderer
DirectWriteGlyphRenderer.draw_options = 0
```

**Comment by DreamAlone666** [comment]
@caffeinepills
You are right.
It do work with `pyglet.font.directwrite.DirectWriteGlyphRenderer.draw_options = 0` and without `pyglet.options['win32_gdi_font'] = True`, 
though the font of `FPSDisplay` seems to be a little thicker(of course, just to the naked eye).

So is it a Windows 7 issue?
Should pyglet 2.0 change the default color options automatically when running on Windows 7?

**Comment by caffeinepills** [comment]
According to the docs it appears that `D2D1_DRAW_TEXT_OPTIONS_ENABLE_COLOR_FONT` is Windows 8.1 and up only. I can make a pull request for it.

**Comment by caffeinepills** [comment]
Should be resolved in master branch now: https://github.com/pyglet/pyglet/commit/5926587a2bb4584cbeca6edd8be1a95b50783bf0

**Comment by DreamAlone666** [comment]
Fixed.

**Comment by DreamAlone666** [comment]
Excuse me , the `Label` still crashes when the `font_size`=0, but it works in pyglet 1.5.

The full python traceback:

Traceback (most recent call last):
  File "d:/Program Files/Temp/pyecs/_临时.py", line 39, in <module>
    run_path('examples/snake.py')
  File "runpy.py", line 265, in run_path
  File "runpy.py", line 97, in _run_module_code
  File "runpy.py", line 87, in _run_code
  File "examples/snake.py", line 160, in <module>
    over_label = pyglet.text.Label('Game Over',
  File "d:\Program Files/Temp/pyecs\pyglet\text\__init__.py", line 481, in __init__
    self.document.set_style(0, len(self.document.text), {
  File "d:\Program Files/Temp/pyecs\pyglet\text\document.py", line 596, in set_style
    return super().set_style(0, len(self.text), attributes)
  File "d:\Program Files/Temp/pyecs\pyglet\text\document.py", line 505, in set_style
    self.dispatch_event('on_style_text', start, end, attributes)
  File "d:\Program Files/Temp/pyecs\pyglet\event.py", line 415, in dispatch_event
    if handler(*args):
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 1497, in on_style_text
    self._init_document()
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 1461, in _init_document
    self._update()
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 1375, in _update
    lines = self._get_lines()
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 1352, in _get_lines
    glyphs = self._get_glyphs()
  File "d:\Program Files/Temp/pyecs\pyglet\text\layout.py", line 1502, in _get_glyphs
    self._document.get_font_runs(dpi=self._dpi),
  File "d:\Program Files/Temp/pyecs\pyglet\text\document.py", line 605, in get_font_runs
    ft = self.get_font(dpi=dpi)
  File "d:\Program Files/Temp/pyecs\pyglet\text\document.py", line 615, in get_font
    return font.load(font_name, font_size, bold=bold, italic=italic, stretch=stretch, dpi=dpi)
  File "d:\Program Files/Temp/pyecs\pyglet\font\__init__.py", line 152, in load
    font = _font_class(name, size, bold=bold, italic=italic, stretch=stretch, dpi=dpi)
  File "d:\Program Files/Temp/pyecs\pyglet\font\directwrite.py", line 1971, in __init__
    self._write_factory.CreateTextFormat(
  File "d:\Program Files/Temp/pyecs\pyglet\libs\win32\com.py", line 150, in _call
    ret = self.method.get_field()(self.i, self.name)(obj, *args)
  File "_ctypes/callproc.c", line 998, in GetResult
OSError: [WinError -2147024809] 参数错误。

**Comment by caffeinepills** [comment]
This is a different error and not related to the original request.

Regardless, you shouldn't be using font size <= 0 as it doesn't display anything. However, this does work for me on Windows 10, so I can only speculate that font size 0 is not a valid size on Windows 7. It's not something that is guaranteed to work on all platforms. You should use label's visible property to set something as visible or not. If for some reason your program relies on such a thing, you can just use the old font renderer with `pyglet.options["win32_gdi_font"] = True` up at the top.
