### ISSUE TITLE
pyglet.gl.ContextException: Could not create GL context when instantiating pyglet.window.Window

### ISSUE THREAD

**Issue by b-schliessmann** [pyglet/pyglet#764]
**Describe the bug**
I'm trying to start a project with pyglets, but run into not really self-explaining errors even with simple things like creating a Window().

I've read in forums that you could edit some source files to edit the minimum required OpenGL version, but **even if** the one my system supports was too low, at least there should be an error message clarifying this. glxgears works fine, I don't know what pyglet's problem is. My hardware (i915)? My MESA version? Something else?

Frankly, I'd just like to use a simple windowing library free of external dependencies for a simple Python-driven UI. It seems that with pyglet, I'm trading external dependencies for cutting-edge hardware requirements. Maybe it should be stated clearly that OpenGL is not only supported, but that a certain version is a hard requirement for using pyglet.

**System Information:**
```
$ python3 -m pyglet.info
Platform
------------------------------------------------------------------------------
platform:  Linux-5.15.0-58-generic-x86_64-with-glibc2.29
release:   5.15.0-58-generic
machine:   x86_64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]
sys.maxint: 9223372036854775807
os.getcwd(): /home/redacted

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.4
pyglet.compat_platform: linux
pyglet.__file__: /home/redacted/.local/lib/python3.8/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['dw_legacy_naming'] = False
pyglet.options['win32_disable_xinput'] = False

pyglet.window
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/info.py", line 183, in _try_dump
    func()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/info.py", line 62, in dump_window
    from pyglet.gl import gl_info
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 191, in <module>
    import pyglet.window
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 133, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 538, in __init__
    context = config.create_context(gl.current_context)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 105, in create_context
    return XlibContext(self, share)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 127, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/info.py", line 183, in _try_dump
    func()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/info.py", line 130, in dump_media
    import pyglet.media
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/media/__init__.py", line 44, in <module>
    from .player import Player, PlayerGroup
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/media/player.py", line 7, in <module>
    from pyglet.gl import GL_TEXTURE_2D
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 191, in <module>
    import pyglet.window
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 133, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 538, in __init__
    context = config.create_context(gl.current_context)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 105, in create_context
    return XlibContext(self, share)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 127, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

pyglet.media.ffmpeg
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/info.py", line 183, in _try_dump
    func()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/info.py", line 138, in dump_ffmpeg
    import pyglet.media
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/media/__init__.py", line 44, in <module>
    from .player import Player, PlayerGroup
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/media/player.py", line 7, in <module>
    from pyglet.gl import GL_TEXTURE_2D
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 191, in <module>
    import pyglet.window
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 133, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 538, in __init__
    context = config.create_context(gl.current_context)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 105, in create_context
    return XlibContext(self, share)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 127, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

pyglet.media.drivers.openal
------------------------------------------------------------------------------
OpenAL not available.

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/media/__init__.py", line 44, in <module>
    from .player import Player, PlayerGroup
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/media/player.py", line 7, in <module>
    from pyglet.gl import GL_TEXTURE_2D
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 191, in <module>
    import pyglet.window
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 133, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 538, in __init__
    context = config.create_context(gl.current_context)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 105, in create_context
    return XlibContext(self, share)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 127, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
```

**How To Reproduce**
```
$ python3 <<EOF
from pyglet.window import Window
w=Window()
EOF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 133, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 538, in __init__
    context = config.create_context(gl.current_context)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 105, in create_context
    return XlibContext(self, share)
  File "/home/redacted/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 127, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
$ glxinfo | grep -i opengl
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics (ILK)
OpenGL version string: 2.1 Mesa 21.2.6
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

**Comment by einarf** [comment]
I suspect that means you should be using 1.5.x and not 2.0.x.

The requirements in 2.0 are definitely not cutting edge. It should work with most hardware created the last 10 years, but of course if you're in an enironment with lacking support/drivers you can always use 1.5.x.

1.5.x is still being maintained.

**Comment by b-schliessmann** [comment]
Hi einarf

So it **is** my hardware, thanks for clarifying. (I'm no OGL expert.) 

It might make sense to add an error message hinting at the issue.

For anyone interested, my workaround at the moment is to use pyglet inside a python interpreter started with "LIBGL_ALWAYS_SOFTWARE=1 python3", which will force software rendering. Since I'm doing simple graphics only, this fits the bill just fine. And I won't have to migrate once 1.5.x will become deprecated.

**Comment by einarf** [comment]
> For anyone interested, my workaround at the moment is to use pyglet inside a python interpreter started with `"LIBGL_ALWAYS_SOFTWARE=1 python3"`, which will force software rendering. Since I'm doing simple graphics only, this fits the bill just fine. And I won't have to migrate once 1.5.x will become deprecated.

Yup this will also work if you have simple needs. Fairly normal to run things like unit tests with it. Can get a decent 30fps. Still there is nothing wrong using pyglet 1.5 I think 😃

**Comment by b-schliessmann** [comment]
> Yup this will also work if you have simple needs. Fairly normal to run things like unit tests with it. Can get a decent 30fps. Still there is nothing wrong using pyglet 1.5 I think

Unfortunately, multisampling isn't supported by the software renderer, but I'm moaning on a high level here ;)

Is there any information for how long 1.5 will be supported? Alas, the link to [roadmap](https://github.com/pyglet/pyglet/wiki/Roadmap) only leads to the github main page.

**Comment by benmoran56** [comment]
There aren't any concrete plans with regards to 1.5, except "as long a people are using it".
Because a lot of people relying on 1.5 are also using legacy systems, we will need to be careful about backporting things.

**Comment by stisa** [comment]
Just wanted to report that I have similar issues with a Raspberry Pi 400 (same hardware as raspberry pi 4). I'll try with the software renderer too, I don't really want to go back to 1.5

**Comment by einarf** [comment]
> Just wanted to report that I have similar issues with a Raspberry Pi 400 (same hardware as raspberry pi 4). I'll try with the software renderer too, I don't really want to go back to 1.5

On raspi 4 it's **really** important to run a distro with a fairly recent mesa version. It's only recentely that V3D drivers was working properly for later GL versions. It's also important to set the pyglet option `opengl_api="gles"` and minor/major version to 3,1. Aka OpenGL ES 3.1.

**Comment by stisa** [comment]
> > Just wanted to report that I have similar issues with a Raspberry Pi 400 (same hardware as raspberry pi 4). I'll try with the software renderer too, I don't really want to go back to 1.5
> 
> On raspi 4 it's **really** important to run a distro with a fairly recent mesa version. It's only recentely that V3D drivers was working properly for later GL versions. It's also important to set the pyglet option `opengl_api="gles"` and minor/major version to 3,1. Aka OpenGL ES 3.1.

interesting, I hadn't seen that config option anywhere, thanks for mentioning it.

**Comment by matanox** [comment]
I'm getting the same error but only for pyglet's `HeadlessContext` object, which I use in tests through:
```
import pyglet; pyglet.options["headless"] = True
```
I have recently installed/re-installed nvidia drivers after adding an old GPU for supporting an additional desktop monitor aside my Intel Graphics, Ubuntu linux supports a desktop using more than one graphics processor as in this case. Not a very new nvidia driver version had to be installed for that old GPU: nvidia driver version 390.157, the newest one supporting the old GPU model I have installed in the machine. 

Does it make sense that this is failing after downgrading or installing GPU drivers? There's no issue normally running my pyglet application, only when run headlessly does this exception rise.

**Comment by matanox** [comment]
Well I guess that the OpenGL version supported is determined by the graphics drivers, so by installing an old (yet otherwise operational) nvidia driver I've probably downgraded the system-wide supported version of OpenGL, for my desktop graphical environment at least, below what pyglet works well for in its latest versions.

**Comment by benmoran56** [comment]
@matanox headless rendering was broken for a time. Try upgrading to the latest pyglet point release. (2.0.20)

**Comment by benmoran56** [comment]
Going to close this ticket as the initial topic has been resolved.

**Comment by matanox** [comment]
Do you prefer a new issue on the same topic? 
I upgraded to the latest pylget release (from 2.0.17 to 2.0.20) but I'm still getting the same. 

My OpenGL information:
```
$ glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 730/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 390.157
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 390.157
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 390.157
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

Does any of this OpenGL version information seem too old for pyglet?

**Comment by matanox** [comment]
I'll move it to a new ticket if preferred.

**Comment by benmoran56** [comment]
That looks fine, as pyglet only needs GL 3.3 (which is over a decade old now). 
Try running `examples/opengl/egl_context.py` to see if the EGL drivers are in place.

**Comment by matanox** [comment]
Does this look fine?

```
EGL version: (1, 4)
Number of configs available:  118
Surface id:  21889697
Context id:  20390385
Buffer type:  EGL_BACK_BUFFER
API type:  EGL_OPENGL_API
```

**Comment by matanox** [comment]
I could not myself confirm from the above that my EGL version is the culprit, and uninstalling the Nvidia drivers might seem to encompass a lot of voodoo possibly worse than the voodoo that made it work in powering the extra attached monitor. 

I didn't notice what was broken in headless rendering for a time before, but upgrading to the latest pyglet point release (2.0.20) didn't make any change in my case.

Might be something specific in my system configuration of EGL that's sneaky.
